"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 项目根目录下的 .env 自动加载（与 manage.py 同级；已存在的环境变量不会被覆盖）
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env", override=True)
except ImportError:
    pass

# 任务默认发布人（FrontendUser.id）：后台与 POST /api/v1/tasks/ 均自动用该用户，无需再选手动发布人
TASK_PLATFORM_PUBLISHER_ID = int(os.environ.get("TASK_PLATFORM_PUBLISHER_ID", "1"))

# Telegram Mini App：`POST /api/v1/auth/telegram/` 与入群校验；优先读后台「第三方集成密钥」表，其次此处。
# 可设环境变量 TELEGRAM_BOT_TOKEN，或复制 core/telegram_secrets.example.py 为 telegram_secrets.py 后填写。
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
try:
    from core import telegram_secrets as _telegram_secrets  # noqa: PLC0415

    _tg = getattr(_telegram_secrets, "TELEGRAM_BOT_TOKEN", "") or ""
    if str(_tg).strip():
        TELEGRAM_BOT_TOKEN = str(_tg).strip()
except ImportError:
    pass

# 邀请链接「t.me/BotUsername?start=ref_xxx」形态：填 Bot 用户名（无 @），与 FoxiGrow 等一致；不配则仍用下方 INVITE_LINK_BASE_URL / 站内路径
TELEGRAM_BOT_USERNAME = os.environ.get("TELEGRAM_BOT_USERNAME", "").strip().lstrip("@")
# 可选：Mini App 短名（BotFather「Direct Link」里的 app 名，如 task_hub_test）；与 TELEGRAM_BOT_USERNAME 同时配置时 invite_link.full_url 为 https://t.me/<bot>/<short>?startapp=…
TELEGRAM_MINI_APP_SHORT_NAME = os.environ.get("TELEGRAM_MINI_APP_SHORT_NAME", "").strip()
# ?start= 参数前缀，默认 ref_（与常见「ref_+TelegramId」一致）
TELEGRAM_INVITE_START_PREFIX = os.environ.get("TELEGRAM_INVITE_START_PREFIX", "ref_").strip() or "ref_"
# Bot Webhook：与 setWebhook 时 secret_token 一致；非空则校验请求头 X-Telegram-Bot-Api-Secret-Token（强烈建议生产必配）
TELEGRAM_WEBHOOK_SECRET = os.environ.get("TELEGRAM_WEBHOOK_SECRET", "").strip()
# 用户点 t.me/bot?start= 后未立刻登录时，待绑定载荷保留时长（秒）
TELEGRAM_START_INVITE_PENDING_TTL_SECONDS = int(
    os.environ.get("TELEGRAM_START_INVITE_PENDING_TTL_SECONDS", str(7 * 24 * 3600))
)

# Twitter / X API v2（只读 Bearer）：用于「绑定推特 + 校验转发/关注」类必做任务
# 优先读 core/twitter_secrets.py（复制 twitter_secrets.example.py 为 twitter_secrets.py 后填写）；否则读环境变量 TWITTER_BEARER_TOKEN
TWITTER_BEARER_TOKEN = os.environ.get("TWITTER_BEARER_TOKEN", "").strip()
try:
    from core import twitter_secrets as _twitter_secrets  # noqa: PLC0415

    _tf = getattr(_twitter_secrets, "TWITTER_BEARER_TOKEN", "") or ""
    if str(_tf).strip():
        TWITTER_BEARER_TOKEN = str(_tf).strip()
except ImportError:
    pass

# Apify：Instagram 简介证明（instagram_proof_link 等）**仅**通过 Apify 校验；须配置 APIFY_API_TOKEN（默认 Actor apify/instagram-profile-scraper）。
APIFY_API_TOKEN = os.environ.get("APIFY_API_TOKEN", "").strip()
APIFY_INSTAGRAM_ACTOR_ID = os.environ.get(
    "APIFY_INSTAGRAM_ACTOR_ID", "apify/instagram-profile-scraper"
).strip()
APIFY_INSTAGRAM_TIMEOUT_SEC = int(os.environ.get("APIFY_INSTAGRAM_TIMEOUT_SEC", "120"))
# Twitter 关注 / 转发校验：优先走 Apify；关注 Actor 默认 scraperx/twitter-user-following-scraper，转发 Actor 默认 api-ninja/x-twitter-replies-retweets-scraper
APIFY_TWITTER_FOLLOW_ACTOR_ID = os.environ.get(
    "APIFY_TWITTER_FOLLOW_ACTOR_ID", "automation-lab/twitter-scraper"
).strip()
APIFY_TWITTER_REPOST_ACTOR_ID = os.environ.get(
    "APIFY_TWITTER_REPOST_ACTOR_ID", "api-ninja/x-twitter-replies-retweets-scraper"
).strip()
APIFY_TWITTER_TIMEOUT_SEC = int(os.environ.get("APIFY_TWITTER_TIMEOUT_SEC", "180"))
APIFY_TWITTER_FOLLOWING_MAX_RESULTS = int(os.environ.get("APIFY_TWITTER_FOLLOWING_MAX_RESULTS", "2000"))
APIFY_TWITTER_AUTH_TOKEN = os.environ.get("APIFY_TWITTER_AUTH_TOKEN", "").strip()
APIFY_TWITTER_CT0 = os.environ.get("APIFY_TWITTER_CT0", "").strip()
# TikTok 绑定转发校验：与 Instagram 共用 APIFY_API_TOKEN；默认 Actor clockworks/tiktok-scraper（profile Reposts）
APIFY_TIKTOK_ACTOR_ID = os.environ.get("APIFY_TIKTOK_ACTOR_ID", "clockworks/tiktok-scraper").strip()
APIFY_TIKTOK_TIMEOUT_SEC = int(os.environ.get("APIFY_TIKTOK_TIMEOUT_SEC", "180"))
APIFY_TIKTOK_RESULTS_PER_PAGE = int(os.environ.get("APIFY_TIKTOK_RESULTS_PER_PAGE", "60"))
try:
    from core import apify_secrets as _apify_secrets  # noqa: PLC0415

    for _k in (
        "APIFY_API_TOKEN",
        "APIFY_INSTAGRAM_ACTOR_ID",
        "APIFY_INSTAGRAM_TIMEOUT_SEC",
        "APIFY_TWITTER_FOLLOW_ACTOR_ID",
        "APIFY_TWITTER_REPOST_ACTOR_ID",
        "APIFY_TWITTER_TIMEOUT_SEC",
        "APIFY_TWITTER_FOLLOWING_MAX_RESULTS",
        "APIFY_TWITTER_AUTH_TOKEN",
        "APIFY_TWITTER_CT0",
        "APIFY_TIKTOK_ACTOR_ID",
        "APIFY_TIKTOK_TIMEOUT_SEC",
        "APIFY_TIKTOK_RESULTS_PER_PAGE",
    ):
        _v = getattr(_apify_secrets, _k, None)
        if _v is not None and str(_v).strip():
            if _k in (
                "APIFY_INSTAGRAM_TIMEOUT_SEC",
                "APIFY_TWITTER_TIMEOUT_SEC",
                "APIFY_TWITTER_FOLLOWING_MAX_RESULTS",
                "APIFY_TIKTOK_TIMEOUT_SEC",
                "APIFY_TIKTOK_RESULTS_PER_PAGE",
            ):
                globals()[_k] = int(_v)
            else:
                globals()[_k] = str(_v).strip()
except ImportError:
    pass

# Mobidea：CPA 任务 postback 校验 secret 与默认 site
MOBIDEA_POSTBACK_SECRET = os.environ.get("MOBIDEA_POSTBACK_SECRET", "").strip()
MOBIDEA_DEFAULT_SITE = os.environ.get("MOBIDEA_DEFAULT_SITE", "taskhub").strip() or "taskhub"

# 已迁移至后台「签到参数配置」中的 weekly_makeup_limit；保留变量仅为兼容旧文档/脚本（新逻辑不再读取）
CHECK_IN_MAKEUPS_PER_WEEK = int(os.environ.get("CHECK_IN_MAKEUPS_PER_WEEK", "3"))

# 个人中心 / 提现（可被环境变量覆盖）
WITHDRAW_MIN_USDT = Decimal(os.environ.get("WITHDRAW_MIN_USDT", "2.00"))
WITHDRAW_FEE_USDT = Decimal(os.environ.get("WITHDRAW_FEE_USDT", "0.00"))
TELEGRAM_COMMUNITY_URL = os.environ.get("TELEGRAM_COMMUNITY_URL", "").strip()
TELEGRAM_ANNOUNCEMENT_URL = os.environ.get("TELEGRAM_ANNOUNCEMENT_URL", "").strip()
TELEGRAM_MINI_APP_URL = os.environ.get("TELEGRAM_MINI_APP_URL", "").strip()
TELEGRAM_BOT_WELCOME_IMAGE_URL = os.environ.get("TELEGRAM_BOT_WELCOME_IMAGE_URL", "").strip()
TELEGRAM_BOT_WELCOME_TEXT = os.environ.get("TELEGRAM_BOT_WELCOME_TEXT", "").replace("\\n", "\n").strip()

# 排行 / 邀请：邀请落地页前缀（勿尾斜杠），如 https://t.me/YourBot?startapp= 或 https://task.example.com
INVITE_LINK_BASE_URL = os.environ.get("INVITE_LINK_BASE_URL", "").strip()
# 邀请返佣比例默认值（后台未配置「邀请返佣配置」时使用）
INVITE_COMMISSION_RATE = Decimal(os.environ.get("INVITE_COMMISSION_RATE", "0.20"))
# 全站「运营天数」起点（YYYY-MM-DD）；不设则用库内最早用户/任务创建日
PLATFORM_STATS_ANCHOR_DATE = os.environ.get("PLATFORM_STATS_ANCHOR_DATE", "").strip()

# 非传统悬赏 interaction=none 之外的玩法：pending 超过该分钟数自动失效
TASK_PENDING_APPLICATION_TIMEOUT_MINUTES = int(
    os.environ.get("TASK_PENDING_APPLICATION_TIMEOUT_MINUTES", "5")
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境务必设置环境变量 SECRET_KEY（勿提交到仓库）
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-=_n0^kny23gwp2c#w((viy8ceje73^5y=e#9=ql$-qr-571zmi",
)

# SECURITY WARNING: don't run with debug turned on in production!
# 生产环境设置 DJANGO_DEBUG=0 或 false
def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


DEBUG = _env_bool("DJANGO_DEBUG", True)

# 使用 HTTPS 域名访问时必填，逗号分隔，例如：https://api.example.com
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# 逗号分隔；用局域网 IP 访问后台时须包含该主机名，例如：ALLOWED_HOSTS=127.0.0.1,localhost,192.168.1.10
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# Nginx 反代终止 HTTPS 时，让 Admin / CSRF 识别 `X-Forwarded-Proto` 与 `Host`（避免「CSRF cookie not set」类误报）
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'wallets',
    'announcements',
    'staking',
    'dashboard',
    'frontend',
    'taskhub',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SimpleCorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.AgentAdminRedirectMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DATABASE", "my_base_db"),
        "USER": os.environ.get("MYSQL_USER", "root"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", "fqf20fqf"),
        "HOST": os.environ.get("MYSQL_HOST", "127.0.0.1"),
        "PORT": os.environ.get("MYSQL_PORT", "3306"),
        "OPTIONS": {
            # 若后台保存报 1785（GTID consistency），多为 django_admin_log / django_session 仍是 MyISAM：
            # ALTER TABLE django_admin_log ENGINE=InnoDB;
            # ALTER TABLE django_session ENGINE=InnoDB;
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# MySQL 开启 GTID 时，若 django_session / django_admin_log 仍为 MyISAM，易与 InnoDB 业务写在同一请求内触发 1785。
# 默认用 Cookie Session，不再写 django_session；后台/CSRF 仍可用（勿在 session 存超大对象）。
# 若必须用数据库 Session，请先执行：ALTER TABLE django_session ENGINE=InnoDB;
# 再设置环境变量：DJANGO_SESSION_ENGINE=django.contrib.sessions.backends.db
SESSION_ENGINE = os.environ.get(
    "DJANGO_SESSION_ENGINE",
    "django.contrib.sessions.backends.signed_cookies",
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_I18N = True

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# 生产环境执行 collectstatic 的输出目录（与 Nginx alias 指向一致）
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# SimpleUI：自定义菜单链接统一用 /admin/ 前缀，避免相对路径解析错误
SIMPLEUI_CONFIG = {
    "system_keep": False,
    "menu_display": ["工作台", "内容中心", "用户增长", "任务运营", "资金结算", "系统配置"],
    "dynamic": False,
    "menus": [
        {
            "name": "工作台",
            "icon": "fas fa-compass",
            "models": [
                {"name": "运营总览", "icon": "fas fa-gauge-high", "url": "/dashboard/"},
                {
                    "name": "首页排行榜统计配置",
                    "icon": "fas fa-chart-line",
                    "url": "/admin/taskhub/platformstatsdisplayconfig/",
                },
                {
                    "name": "接口目录",
                    "icon": "fas fa-book",
                    "url": "/api/v1/docs/",
                },
                {
                    "name": "接口文档",
                    "icon": "fas fa-file-alt",
                    "url": "/docs/taskhub-api/",
                },
            ],
        },
        {
            "name": "内容中心",
            "icon": "fas fa-bullhorn",
            "models": [
                {
                    "name": "系统公告",
                    "icon": "fas fa-volume-high",
                    "url": "/admin/announcements/announcement/?post_type__exact=announcement",
                },
                {
                    "name": "指南分类",
                    "icon": "fas fa-tags",
                    "url": "/admin/announcements/guidecategory/",
                },
                {
                    "name": "新手指南",
                    "icon": "fas fa-edit",
                    "url": "/admin/announcements/announcement/?post_type__exact=newbie_guide",
                },
                {
                    "name": "在线反馈",
                    "icon": "fas fa-headset",
                    "url": "/admin/taskhub/onlinefeedback/",
                },
            ],
        },
        {
            "name": "用户增长",
            "icon": "fas fa-users",
            "models": [
                {"name": "会员列表", "icon": "far fa-user", "url": "/admin/users/frontenduser/"},
                {
                    "name": "邀请返佣配置",
                    "icon": "fas fa-percent",
                    "url": "/admin/taskhub/referralrewardconfig/",
                },
                {
                    "name": "会员等级活动配置",
                    "icon": "fas fa-crown",
                    "url": "/admin/taskhub/membershiplevelconfig/",
                },
                {
                    "name": "团队长扶持阶梯",
                    "icon": "fas fa-people-group",
                    "url": "/admin/taskhub/teamleadertier/",
                },
                {
                    "name": "邀请成就配置",
                    "icon": "fas fa-trophy",
                    "url": "/admin/taskhub/inviteachievementtier/",
                },
                {
                    "name": "邀请成就记录",
                    "icon": "fas fa-medal",
                    "url": "/admin/taskhub/inviteachievementclaim/",
                },
                {
                    "name": "代理账号开通",
                    "icon": "fas fa-user-shield",
                    "url": "/admin/users/agentprofile/",
                },
            ],
        },
        {
            "name": "任务运营",
            "icon": "fas fa-list-check",
            "models": [
                {"name": "任务分类", "icon": "fas fa-folder-open", "url": "/admin/taskhub/taskcategory/"},
                {"name": "任务列表", "icon": "fas fa-clipboard-list", "url": "/admin/taskhub/task/"},
                {"name": "任务报名", "icon": "fas fa-user-check", "url": "/admin/taskhub/taskapplication/"},
                {
                    "name": "截图任务审核",
                    "icon": "fas fa-image",
                    "url": "/admin/taskhub/screenshotproofreview/",
                },
                {
                    "name": "任务完成记录",
                    "icon": "fas fa-check-circle",
                    "url": "/admin/taskhub/taskcompletionrecord/",
                },
                {"name": "签到参数配置", "icon": "fas fa-calendar-check", "url": "/admin/taskhub/checkinconfig/"},
                {"name": "签到记录", "icon": "fas fa-calendar-alt", "url": "/admin/taskhub/checkinrecord/"},
                {
                    "name": "每日任务配置",
                    "icon": "fas fa-sun",
                    "url": "/admin/taskhub/dailytaskdefinition/",
                },
                {
                    "name": "每日任务记录",
                    "icon": "fas fa-check-double",
                    "url": "/admin/taskhub/dailytaskdayclaim/",
                },
            ],
        },
        {
            "name": "资金结算",
            "icon": "fas fa-wallet",
            "models": [
                {
                    "name": "充值网络配置",
                    "icon": "fas fa-link",
                    "url": "/admin/wallets/rechargenetworkconfig/",
                },
                {
                    "name": "用户充值地址",
                    "icon": "fas fa-address-card",
                    "url": "/admin/wallets/userrechargeaddress/",
                },
                {
                    "name": "充值流水",
                    "icon": "fas fa-coins",
                    "url": "/admin/wallets/rechargerequest/",
                },
                {"name": "账变记录", "icon": "fas fa-receipt", "url": "/admin/wallets/transaction/"},
                {
                    "name": "提现申请",
                    "icon": "fas fa-money-bill-transfer",
                    "url": "/admin/wallets/withdrawalrequest/",
                },
            ],
        },
        {
            "name": "系统配置",
            "icon": "fas fa-sliders",
            "models": [
                {
                    "name": "第三方集成密钥",
                    "icon": "fas fa-plug",
                    "url": "/admin/taskhub/integrationsecretconfig/",
                },
                {
                    "name": "接口令牌",
                    "icon": "fas fa-key",
                    "url": "/admin/taskhub/apitoken/",
                },
                {"name": "后台账号", "icon": "fas fa-user-cog", "url": "/admin/auth/user/"},
                {"name": "权限分组", "icon": "fas fa-user-group", "url": "/admin/auth/group/"},
            ],
        },
    ],
}


SIMPLEUI_HOME_INFO = False
SIMPLEUI_LOGO = "https://avatars.githubusercontent.com/u/23233045?s=200&v=4"

# Django Admin 后台标题配置
ADMIN_SITE_HEADER = "TaskHub 运营后台"
ADMIN_SITE_TITLE = "TaskHub"
ADMIN_INDEX_TITLE = "业务管理与配置中心"

# 服务器本地覆盖：存在 core/local_settings.py 时加载（不依赖 .env；见 local_settings.example.py）
try:
    from core.local_settings import *  # noqa: F403, E402
except ImportError:
    pass


def _ensure_simpleui_menu_item(group_name, item):
    """Keep required admin links visible even when local_settings overrides menus."""
    try:
        menu_display = SIMPLEUI_CONFIG.setdefault("menu_display", [])
        if group_name not in menu_display:
            menu_display.append(group_name)
        menus = SIMPLEUI_CONFIG.setdefault("menus", [])
    except NameError:
        return

    group = next((menu for menu in menus if menu.get("name") == group_name), None)
    if group is None:
        group = {"name": group_name, "icon": "fas fa-folder", "models": []}
        menus.append(group)

    models = group.setdefault("models", [])
    if not any(model.get("name") == item["name"] or model.get("url") == item["url"] for model in models):
        models.append(item)


_ensure_simpleui_menu_item(
    "内容中心",
    {
        "name": "在线反馈",
        "icon": "fas fa-headset",
        "url": "/admin/taskhub/onlinefeedback/",
    },
)

# 追加域名（逗号分隔），无需改 local_settings.py；Supervisor / 宝塔「环境变量」里设 ALLOWED_HOSTS_EXTRA 即可
_extra_hosts = os.environ.get("ALLOWED_HOSTS_EXTRA", "").strip()
if _extra_hosts:
    _merged = [h.strip() for h in ALLOWED_HOSTS if str(h).strip()]
    for h in _extra_hosts.split(","):
        h = h.strip()
        if h and h not in _merged:
            _merged.append(h)
    ALLOWED_HOSTS = _merged
